### ISSUE TITLE
Add license

### ISSUE THREAD

**Issue by Entjaman** [cansik/spout-spyhon-rgbd-example#1]
Hi Cansik,

I am interested in tinkering with this repo, however, since it does not have any License I want to respect your work and do not create any derivative works.

Is it possible for you to add some kind of license? I saw that in the pip-package it is under MIT license, but the github repo needs to be updated as well as far as I understand.

Discussion on the topic: https://opensource.stackexchange.com/questions/1720/what-can-i-assume-if-a-publicly-published-project-has-no-license

Thank you!
//Entjaman

**Comment by cansik** [comment]
Thanks, the MIT license has been added to the repository.
